### ISSUE TITLE
Build error… 

### ISSUE THREAD

**Issue by jamiedawsonyoung** [ubuntudesign/snapcraft.io#1]
Hey @anthonydillon I got all excited and tried to build this locally but it didn't work :-( I sat with Karl and Graham but we still couldn't work out why (and then Magda noticed I was taking up their time) ;-)

The error I get is this: 

```
(node:1292) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[10:18:30] Using gulpfile ~/Sites/snapcraft.io/Gulpfile.js
[10:18:30] Starting 'jekyll-build'...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn jekyll ENOENT
    at exports._errnoException (util.js:953:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:449:3
```

Can you help?! 

P.s I had a wee look on Graham's mac, it's looking nice. (I thought you might be asked to do that this week) ;-)

**Comment by anthonydillon** [comment]
Just try to run `jekyll serve` and hopefully that should run the server.
Otherwise we can catch up on Monday and get it running.

**Comment by anthonydillon** [comment]
The issue was missing global Sass installation.
